import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MainNav, ThemeChanger } from "@/components/NavBars";
import SocialsCard from "@/components/Socials";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" style={{colorScheme: "light"}}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <MainNav className="fixed top-1 left-1/2 transform -translate-x-1/2 z-99" />
          <ThemeChanger className="fixed top-3 right-10 transform translate-x-1/2 z-99" />
          {children}
          <SocialsCard className="fixed bottom-4 right-4" />
        </ThemeProvider>
      </body>
    </html>
  );
}
{
  /* <ThemeProvider attribute="data-mode"></ThemeProvider> */
}
