import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { MainNav } from "@/components/NavBars";
import SocialsCard from "@/components/Socials";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          `${geistSans.variable} ${geistMono.variable}`,
          "antialiased relative"
        )}
      >
        <MainNav className="fixed top-5 left-1/2 transform -translate-x-1/2 z-99" />
        {children}
        <SocialsCard className="fixed bottom-4 right-4" />
      </body>
    </html>
  );
}
